spring.application.name=api-Pagos-service
server.port=8095
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.config.import=configserver:http://localhost:8888
management.endpoints.web.exposure.include=health,info,refresh
